name: 'Build and Deploy'
description:  'Build and Deploy'
inputs:
  pypi-token:
    description: 'PyPI API token'
    required: true

runs:
    using: 'composite'
    steps:
      - name: set up uv and install dependencies
        uses: astral-sh/setup-uv@v7
      - name: Build package
        run: |
          make build
        shell: bash
      - name: Publish package
        run: |
          export UV_PUBLISH_TOKEN=${{ inputs.pypi-token }}
          make publish
        shell: bash
