name: Release mermaid-py package

on:
  workflow_dispatch:
    inputs:
      bump-type:
        description: 'Bump type'
        required: true
        default: 'patch'
        options:
          - patch
          - minor
          - major

permissions:
  contents: write

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0
    - name: bump version
      uses: ouhammmourachid/bumpversion-action@v1.1.0
      with:
        bump-type: ${{ github.event.inputs.bump-type }}
        github-token: ${{ github.token }}

    - name: Build and Deploy to PyPI
      uses: ./.github/actions/build-deploy
      with:
        pypi-token: ${{ secrets.PYPI_API_TOKEN }}
